out_dir: data/models/base_M/

optim: SGD
lr: 0.01
momentum: 0.9
weight_decay: 0.0001
scheduler: MultiStepLR
gamma: 0.5 
milestones: [4, 8, 12, 13, 14, 15]
momentum: 0.9
weight_decay: 0.0001

model_params:
  # arch: resnet50 # model architecture from torchvision namespace
  # weights: null # null -> all models are initialized with "ImageNet" weights or path to .ckpt to initialize from pre-trained model
  batch_size: 128
  # partitionings:
  #   ptype: default
  #   shortnames: [coarse, middle, fine]
  #   files:
  #     - resources/s2_cells/cells_50_5000.csv
  #     - resources/s2_cells/cells_50_2000.csv
  #     - resources/s2_cells/cells_50_1000.csv
  # images stored in chunks
  msgpack_train_dir: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/mp16
  msgpack_train_dir2: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/mp16/mp16_rgb_images/
  msgpack_train_seg_dir: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/mp16/mp16_seg_images_PNG/
  msgpack_val_dir: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/yfcc25600
  msgpack_val_dir2: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/yfcc25600/yfcc25600_rgb_images/
  msgpack_val_seg_dir: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/yfcc25600/yfcc25600_seg_images_PNG/
  msgpack_test_dir: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/im2gps/im2gps_rgb_images/
  msgpack_test_seg_dir: /cis/home/enowara/Muller/GeoEstimation-master/resources/images/im2gps/im2gps_seg_images_PNG/
  # meta information i.e. coordinates for each image
  train_meta_path: /cis/home/enowara/Muller/GeoEstimation-master/resources/mp16_places365.csv
  val_meta_path: /cis/home/enowara/Muller/GeoEstimation-master/resources/yfcc25600_places365.csv
  test_meta_path: /cis/home/enowara/Muller/GeoEstimation-master/resources/im2gps_places365.csv
  # mapping from image ids in msgpack dataset to target value(s)
  # orient: index -> {"img_id": [t1, t2], ...}
  train_label_mapping: /cis/home/enowara/Muller/GeoEstimation-master/resources/mp16_places365_mapping_h3.json
  val_label_mapping: /cis/home/enowara/Muller/GeoEstimation-master/resources/yfcc_25600_places365_mapping_h3.json
  segment_file_path: /cis/home/enowara/Muller/GeoEstimation-master/resources/semantic_cagtegories.mat
  key_img_id: id # image id name for msgpack dataset
  key_img_encoded: image # image data name for msgpack dataset
  num_workers_per_loader: 4
  # scene_of_interest: 1 # indoor - 0, natural - 1, urban - 2, all - 3
  #seg_channels: 150 # 3
  percent_seg_pixels: 1 # 3
# num_workers_per_loader: 6
# paramters for pytorch lightning trainer class
# trainer_params:
#   gpus: 1
#   max_epochs: 15
#   distributed_backend: null
#   precision: 16
#   reload_dataloaders_every_epoch: true # necessary to shuffle IterableDataset

